<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Paling SesuaiUlasanTerbaruHarga TertinggiHarga Terendah</name>
   <tag></tag>
   <elementGuidId>d237a8af-11c2-4e0a-aa55-a4f1ed2b05da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-xgs9eh.e17suhym1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::div[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>75f88854-6c33-415a-8886-6328fa71d95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>c0dcdf74-9c34-45d8-9b25-8ccf1a37135d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>77952b6a-1047-481d-80d1-110429a1dba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unify</name>
      <type>Main</type>
      <value>Dropdown</value>
      <webElementGuid>e1daa2d6-576e-4160-8036-c91126de1666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-xgs9eh e17suhym1</value>
      <webElementGuid>ee63682b-9fad-4f75-9c8e-ee1cdcfffb00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dropdown-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>05d30906-110b-435b-82c7-b4b5d4bd1b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Paling SesuaiUlasanTerbaruHarga TertinggiHarga Terendah</value>
      <webElementGuid>272c07f3-647f-4a7e-878c-0bc4829121f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[6]/div[@class=&quot;css-xgs9eh e17suhym1&quot;]</value>
      <webElementGuid>36c68146-166a-424b-8e0f-e0c12f2b143d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::div[7]</value>
      <webElementGuid>a8c6538a-445e-4d4f-9bf8-fc678d156643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia'])[1]/following::div[7]</value>
      <webElementGuid>a2e02cd3-acc0-4311-82cb-56ea1377b86f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[14]</value>
      <webElementGuid>cef8ec94-e849-42fd-b3a0-caf1b1b23064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::div[14]</value>
      <webElementGuid>37d4f21d-7e51-4d7b-af86-81f8a51a4b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
      <webElementGuid>6242ef1b-5d05-4bc2-875c-999276f460ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Paling SesuaiUlasanTerbaruHarga TertinggiHarga Terendah' or . = 'Paling SesuaiUlasanTerbaruHarga TertinggiHarga Terendah')]</value>
      <webElementGuid>42ca256d-bc9e-496b-8962-2f6bd35d7667</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
